---
#title: cBioPortal Data Collection
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: 0;
  margin-right: 0;
}

h1.title {
  font-size: 14px;
  color: DarkRed;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{bash echo=TRUE, message=FALSE, eval=FALSE}

####################################################################
#######              ArrayExpress Data Collection            #######
####################################################################

### E-MTAB-26 dataset as an example
wget https://www.ebi.ac.uk/arrayexpress/files/E-TABM-26/E-TABM-26.sdrf.txt
wget https://www.ebi.ac.uk/arrayexpress/files/E-TABM-26/E-TABM-26.raw.1.zip
wget https://www.ebi.ac.uk/arrayexpress/files/E-TABM-26/E-TABM-26.raw.2.zip
wget https://www.ebi.ac.uk/arrayexpress/files/E-TABM-26/E-TABM-26.raw.3.zip
unzip E-TABM-26.raw.1.zip -d E-TABM-26/
unzip E-TABM-26.raw.1.zip -d E-TABM-26/
unzip E-TABM-26.raw.1.zip -d E-TABM-26/

mkdir E-TABM-26/U133A E-TABM-26/U133B
mv E-TABM-26/^B*CEL E-TABM-26/U133B/
mv E-TABM-26/*B.CEL E-TABM-26/U133B/
mv E-TABM-26/*.CEL E-TABM-26/U133A/

```


```{r echo=TRUE, message=FALSE, eval=FALSE}

# install.packages("http://mbni.org/customcdf/24.0.0/gencodeg.download/pd.hgu133a.hs.gencodeg_24.0.0.tar.gz",
#                  repos = NULL, type = "source")

library(oligo)
library(pd.hgu133a.hs.gencodeg)

################## Expression Data ##################

dataset <- 'E-TABM-26-U133A'

### 133A
celFiles <- list.celfiles(paste0('data/fromArrayExpress/E-MTAB-26/U133A/'), full.names=T, listGzipped=T)
rawData <- read.celfiles(celFiles, pkgname = 'pd.hgu133a.hs.gencodeg')
probesetData <- oligo::rma(rawData)
exprData <- exprs(probesetData)

colnames(exprData) <- unlist(lapply(colnames(exprData), function(x) strsplit(x, '.', fixed=T)[[1]][1]))
rownames(exprData) <- unlist(lapply(rownames(exprData), function(x) strsplit(x, '.', fixed=T)[[1]][1]))
#colnames(exprData) <- unlist(lapply(colnames(exprData), function(x) strsplit(x, '_', fixed=T)[[1]][1]))

exprData <- exprData[which(startsWith(rownames(exprData), 'ENSG')),]

################## Metadata ##################

pheno <- read.delim('data/fromArrayExpress/E-TABM-26/E-TABM-26.sdrf.txt',
                   header = T, sep = '\t', stringsAsFactors = F)

rownames(pheno) <- unlist(lapply(pheno$Array.Data.File, function(x) strsplit(x, '.', fixed=T)[[1]][1]))

pheno[pheno=='-'] <- NA
pheno[pheno=='unknown'] <- NA

### Harmonized metadata
traits <- c('sample_id','patient_id','tissue','batch','platform','sample_type',
            'age_at_diagnosis','ethnicity','race','clinical_stage','clinical_t_stage',
            'clinical_n_stage','clinical_m_stage','pathological_stage','pathological_t_stage',
            'pathological_n_stage','pathological_m_stage','preop_psa','gleason_primary_pattern',
            'gleason_secondary_pattern','gleason_tertiary_pattern','gleason_group','gleason_score',
            'time_to_death','os_status','time_to_bcr','bcr_status','time_to_metastasis',
            'metastasis_status','risk_group','treatment','additional_treatment')

phenoData <- data.frame(matrix(NA, nrow=nrow(pheno), ncol=length(traits)), stringsAsFactors = F)

colnames(phenoData) <- traits
rownames(phenoData) <- rownames(pheno)

phenoData$sample_id <- pheno$Source.Name
phenoData$patient_id <- pheno$Characteristics..Individual.
phenoData$sample_type <- ifelse(pheno$Characteristics..DiseaseState.=='normal', 'Normal', 'Primary')
phenoData$platform <- 'Affymetrix Human Genome U133A Array'
phenoData$age_at_diagnosis <- pheno$Characteristics..Age.
phenoData$pathological_t_stage <- pheno$Characteristics..DiseaseStaging.

################## ExpressionSet ##################
ovlp <- intersect(rownames(phenoData), colnames(exprData))

exprData <- exprData[,ovlp]
phenoData <- phenoData[ovlp,]

all(rownames(phenoData) == colnames(exprData))

eSet <- ExpressionSet(assayData = as.matrix(exprData),
                      phenoData = AnnotatedDataFrame(phenoData))

saveRDS(eSet, file=paste0('data/Database/', dataset, '_eSet.RDS'))
```
