---
#title: cBioPortal Data Collection
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: 0;
  margin-right: 0;
}

h1.title {
  font-size: 14px;
  color: DarkRed;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{bash echo=TRUE, message=FALSE, eval=FALSE}

####################################################################
#######               cBioPortal Data Collection             #######
####################################################################

### DKFZ dataset as an example
wget https://cbioportal-datahub.s3.amazonaws.com/prostate_dkfz_2018.tar.gz
tar -xvzf prostate_dkfz_2018.tar.gz

```


```{r echo=TRUE, message=FALSE, eval=FALSE}
dataset <- 'DKFZ'

################## Expression Data ##################

exprData <- read.table('data/cBioPortal/prostate_dkfz_2018_RNA_Seq_expression_median.txt',
                       sep='\t', header = T, stringsAsFactors = F)

## ENSEMBL 62; ftp://ftp.ensembl.org/pub/release-62/gtf/homo_sapiens/
gtf <- readGFF('data/Annotation/Homo_sapiens.GRCh37.62.gtf.gz', version=2L)
filter <- which(duplicated(gtf$gene_id))
gtf <- gtf[-filter,]
gtf

exprData <- add_column(.data = exprData, .before = 3, Ensembl=NA)
exprData$Ensembl <- gtf$gene_id[match(exprData$Hugo_Symbol, gtf$gene_name)]
exprData[1:5,1:5]

filter <- which(duplicated(exprData$Ensembl))
filter

exprData <- exprData[-filter,]
rownames(exprData) <-exprData$Ensembl

exprData <- exprData[,-c(1:3)]

################## Metadata ##################

pheno <- read.table('data/cBioPortal/prostate_dkfz_2018_clinical_data.tsv', 
                    sep='\t', header=T, stringsAsFactors = F)

rownames(pheno) <- pheno$Sample.ID

### Harmonized metadata
traits <- c('sample_id','patient_id','tissue','batch','platform','sample_type',
            'age_at_diagnosis','ethnicity','race','clinical_stage','clinical_t_stage',
            'clinical_n_stage','clinical_m_stage','pathological_stage','pathological_t_stage',
            'pathological_n_stage','pathological_m_stage','preop_psa','gleason_primary_pattern',
            'gleason_secondary_pattern','gleason_tertiary_pattern','gleason_group','gleason_score',
            'time_to_death','os_status','time_to_bcr','bcr_status','time_to_metastasis',
            'metastasis_status','risk_group','treatment','additional_treatment')

phenoData <- data.frame(matrix(NA, nrow=nrow(pheno), ncol=length(traits)), stringsAsFactors = F)

colnames(phenoData) <- traits
rownames(phenoData) <- rownames(pheno)

phenoData$sample_id <- pheno$Sample.ID
phenoData$patient_id <- pheno$Patient.ID
phenoData$platform <- 'Illumina HiSeq 2000 (50bp paired-end)'
phenoData$sample_type <- 'Primary'
phenoData$age_at_diagnosis <- pheno$Diagnosis.Age
phenoData$pathological_stage <- pheno$Stage
phenoData$preop_psa <- pheno$Preop.PSA
phenoData$gleason_primary_pattern <- as.numeric(lapply(pheno$Radical.Prostatectomy.Gleason.Score.for.Prostate.Cancer, function(x) strsplit(x, '+', fixed=T)[[1]][1]))
phenoData$gleason_secondary_pattern <- as.numeric(lapply(pheno$Radical.Prostatectomy.Gleason.Score.for.Prostate.Cancer, function(x) strsplit(x, '+', fixed=T)[[1]][2]))
phenoData$gleason_score <- phenoData$gleason_primary_pattern + phenoData$gleason_secondary_pattern
phenoData$gleason_group <- ifelse(is.na(phenoData$gleason_score), NA, paste(phenoData$gleason_primary_pattern, phenoData$gleason_secondary_pattern, sep='+'))
phenoData$time_to_bcr <- as.numeric(pheno$Time.from.Surgery.to.BCR.Last.Follow.Up)
phenoData$bcr_status <- as.numeric(pheno$BCR.Status)

################## ExpressionSet ##################
ovlp <- intersect(rownames(phenoData), colnames(exprData))

exprData <- exprData[,ovlp]
phenoData <- phenoData[ovlp,]

all(rownames(phenoData) == colnames(exprData))

eSet <- ExpressionSet(assayData = as.matrix(exprData),
                      phenoData = AnnotatedDataFrame(phenoData))

saveRDS(eSet, file=paste0('data/Database/', dataset, '_eSet.RDS'))

```
